
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 11.5 EDK_LS5.70
* DO NOT EDIT.
*
* Copyright (c) 1995-2009 Xilinx, Inc.  All rights reserved.

* 
* Description: Configurations for Standalone BSP
*
*******************************************************************/

#define MICROBLAZE_PVR_NONE
