
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 11.5 EDK_LS5.70
* DO NOT EDIT.
*
* Copyright (c) 1995-2009 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartlite.h"

/*
* The configuration table for devices
*/

XUartLite_Config XUartLite_ConfigTable[] =
{
	{
		XPAR_RS232_0_DEVICE_ID,
		XPAR_RS232_0_BASEADDR,
		XPAR_RS232_0_BAUDRATE,
		XPAR_RS232_0_USE_PARITY,
		XPAR_RS232_0_ODD_PARITY,
		XPAR_RS232_0_DATA_BITS
	}
};


