
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 11.5 EDK_LS5.70
* DO NOT EDIT.
*
* Copyright (c) 1995-2009 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xsysmon.h"

/*
* The configuration table for devices
*/

XSysMon_Config XSysMon_ConfigTable[] =
{
	{
		XPAR_XPS_SYSMON_ADC_0_DEVICE_ID,
		XPAR_XPS_SYSMON_ADC_0_BASEADDR,
		XPAR_XPS_SYSMON_ADC_0_INCLUDE_INTR
	}
};


