#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/proj/users/hmnguyen/qmfir/qmfir_eth/qmfir_udp/EDK_project/system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /proj/sw/Xilinx/11.1/EDK
NON_CYG_XILINX_EDK_DIR = /proj/sw/Xilinx/11.1/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = virtex5

DEVICE = xc5vfx130tff1738-1

LANGUAGE = vhdl

SEARCHPATHOPT = 
GLOBAL_SEARCHPATHOPT = 

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT) -msg __xps/ise/xmsgprops.lst

OBSERVE_PAR_OPTIONS = -error no

ISHELL_OUTPUT_DIR = sw_src/ishell
ISHELL_OUTPUT = $(ISHELL_OUTPUT_DIR)/executable.elf

DEMO_UDP_OUTPUT_DIR = sw_src/demo_udp
DEMO_UDP_OUTPUT = $(DEMO_UDP_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

PPC440_0_BOOTLOOP = $(BOOTLOOP_DIR)/ppc440_0.elf

BRAMINIT_ELF_FILES =   $(PPC440_0_BOOTLOOP) 
BRAMINIT_ELF_FILE_ARGS =   -pe ppc440_0  $(PPC440_0_BOOTLOOP) 

ALL_USER_ELF_FILES = $(ISHELL_OUTPUT) $(DEMO_UDP_OUTPUT) 

SIM_CMD = /proj/sw/ModelSim/modeltech/bin/vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT) -msg __xps/ise/xmsgprops.lst -s mti -X /proj/sw/Xilinx/11.1/ISE/verilog/mti_se/6.5c/lin


LIBRARIES =  \
       ppc440_0/lib/libxil.a 

LIBSCLEAN_TARGETS = ppc440_0_libsclean 

PROGRAMCLEAN_TARGETS = iShell_programclean demo_udp_programclean 

CORE_STATE_DEVELOPMENT_FILES = /proj/users/hmnguyen/qmfir/qmfir_eth/qmfir_udp/EDK_project/pcores/qmfir_v1_00_a/netlist/BRAM.ngc \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/proc_common_pkg.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/ipif_pkg.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_muxcy.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_gate128.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/family_support.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pselect_f.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/counter_f.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/inferred_lut4.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_counter_bit.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_counter.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_counter_top.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_occ_counter.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_occ_counter_top.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_adder_bit.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_adder.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pf_dpram_select.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl16_fifo.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_slave_single_v1_01_a/hdl/vhdl/plb_address_decoder.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_slave_single_v1_01_a/hdl/vhdl/plb_slave_attachment.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_slave_single_v1_01_a/hdl/vhdl/plbv46_slave_single.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/interrupt_control_v2_01_a/hdl/vhdl/interrupt_control.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/wrpfifo_v5_00_a/hdl/vhdl/pf_dly1_mux.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/wrpfifo_v5_00_a/hdl/vhdl/wrpfifo_dp_cntl.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/wrpfifo_v5_00_a/hdl/vhdl/ipif_control_wr_dre.vhd \
/proj/sw/Xilinx/11.1/EDK/hw/XilinxProcessorIPLib/pcores/wrpfifo_v5_00_a/hdl/vhdl/wrpfifo_top.vhd \
pcores/qmfir_v1_00_a/hdl/verilog/user_logic.v \
pcores/qmfir_v1_00_a/hdl/verilog/BRAM.v \
pcores/qmfir_v1_00_a/hdl/vhdl/qmfir.vhd

WRAPPER_NGC_FILES = implementation/xps_timer_0_wrapper.ngc \
implementation/xps_sysmon_adc_0_wrapper.ngc \
implementation/xps_intc_0_wrapper.ngc \
implementation/xps_bram_if_cntlr_0_bram_wrapper.ngc \
implementation/xps_bram_if_cntlr_0_wrapper.ngc \
implementation/proc_sys_reset_0_wrapper.ngc \
implementation/ppc440_0_wrapper.ngc \
implementation/plb_v46_0_wrapper.ngc \
implementation/jtagppc_cntlr_inst_wrapper.ngc \
implementation/clock_generator_0_wrapper.ngc \
implementation/rs232_0_wrapper.ngc \
implementation/hard_ethernet_mac_fifo_wrapper.ngc \
implementation/hard_ethernet_mac_wrapper.ngc \
implementation/ddr_sdram_0_wrapper.ngc \
implementation/qmfir_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

SDK_EXPORT_DIR = SDK/SDK_Export/hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_BMM = $(SDK_EXPORT_DIR)/$(SYSTEM)_bd.bmm
SYSTEM_HW_HANDOFF_DEP = $(SYSTEM_HW_HANDOFF) $(SYSTEM_HW_HANDOFF_BIT) $(SYSTEM_HW_HANDOFF_BMM)

#################################################################
# SOFTWARE APPLICATION ISHELL
#################################################################

ISHELL_SOURCES = sw_src/ishell/ishell.c 

ISHELL_HEADERS = 

ISHELL_CC = powerpc-eabi-gcc
ISHELL_CC_SIZE = powerpc-eabi-size
ISHELL_CC_OPT = -O2
ISHELL_CFLAGS = 
ISHELL_CC_SEARCH = # -B
ISHELL_LIBPATH = -L./ppc440_0/lib/ # -L
ISHELL_INCLUDES = -I./ppc440_0/include/ # -I
ISHELL_LFLAGS = # -l
ISHELL_LINKER_SCRIPT = 
ISHELL_LINKER_SCRIPT_FLAG = #-Wl,-T -Wl,$(ISHELL_LINKER_SCRIPT) 
ISHELL_CC_DEBUG_FLAG =  -g 
ISHELL_CC_PROFILE_FLAG = # -pg
ISHELL_CC_GLOBPTR_FLAG= # -msdata=eabi
ISHELL_CC_INFERRED_FLAGS= -mcpu=440 
ISHELL_CC_START_ADDR_FLAG= -Wl,-defsym -Wl,_START_ADDR=0xffff8000
ISHELL_CC_STACK_SIZE_FLAG= -Wl,-defsym -Wl,_STACK_SIZE=0x1000
ISHELL_CC_HEAP_SIZE_FLAG= -Wl,-defsym -Wl,_HEAP_SIZE=0x1000
ISHELL_OTHER_CC_FLAGS= $(ISHELL_CC_GLOBPTR_FLAG)  \
                  $(ISHELL_CC_START_ADDR_FLAG) $(ISHELL_CC_STACK_SIZE_FLAG) $(ISHELL_CC_HEAP_SIZE_FLAG)  \
                  $(ISHELL_CC_INFERRED_FLAGS)  \
                  $(ISHELL_LINKER_SCRIPT_FLAG) $(ISHELL_CC_DEBUG_FLAG) $(ISHELL_CC_PROFILE_FLAG) 

#################################################################
# SOFTWARE APPLICATION DEMO_UDP
#################################################################

DEMO_UDP_SOURCES = sw_src/demo_udp/int_setup.c sw_src/demo_udp/main.c sw_src/demo_udp/qmfir_comm.c sw_src/demo_udp/qmfir.c 

DEMO_UDP_HEADERS = sw_src/demo_udp/int_setup.h sw_src/demo_udp/qmfir_comm.h sw_src/demo_udp/qmfir.h 

DEMO_UDP_CC = powerpc-eabi-gcc
DEMO_UDP_CC_SIZE = powerpc-eabi-size
DEMO_UDP_CC_OPT = -O2
DEMO_UDP_CFLAGS = 
DEMO_UDP_CC_SEARCH = # -B
DEMO_UDP_LIBPATH = -L./ppc440_0/lib/ # -L
DEMO_UDP_INCLUDES = -I./ppc440_0/include/  -Isw_src/demo_udp/ # -I
DEMO_UDP_LFLAGS =   -llwip4 
DEMO_UDP_LINKER_SCRIPT = 
DEMO_UDP_LINKER_SCRIPT_FLAG = #-Wl,-T -Wl,$(DEMO_UDP_LINKER_SCRIPT) 
DEMO_UDP_CC_DEBUG_FLAG =  -g 
DEMO_UDP_CC_PROFILE_FLAG = # -pg
DEMO_UDP_CC_GLOBPTR_FLAG= # -msdata=eabi
DEMO_UDP_CC_INFERRED_FLAGS= -mcpu=440 
DEMO_UDP_CC_START_ADDR_FLAG= -Wl,-defsym -Wl,_START_ADDR=0x00000000
DEMO_UDP_CC_STACK_SIZE_FLAG= -Wl,-defsym -Wl,_STACK_SIZE=0x40000
DEMO_UDP_CC_HEAP_SIZE_FLAG= -Wl,-defsym -Wl,_HEAP_SIZE=0x40000
DEMO_UDP_OTHER_CC_FLAGS= $(DEMO_UDP_CC_GLOBPTR_FLAG)  \
                  $(DEMO_UDP_CC_START_ADDR_FLAG) $(DEMO_UDP_CC_STACK_SIZE_FLAG) $(DEMO_UDP_CC_HEAP_SIZE_FLAG)  \
                  $(DEMO_UDP_CC_INFERRED_FLAGS)  \
                  $(DEMO_UDP_LINKER_SCRIPT_FLAG) $(DEMO_UDP_CC_DEBUG_FLAG) $(DEMO_UDP_CC_PROFILE_FLAG) 
