
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 11.5 EDK_LS5.70
* DO NOT EDIT.
*
* Copyright (c) 1995-2009 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmpmc.h"

/*
* The configuration table for devices
*/

XMpmc_Config XMpmc_ConfigTable[] =
{
	{
		XPAR_DDR_SDRAM_0_DEVICE_ID,
		XPAR_DDR_SDRAM_0_MPMC_BASEADDR,
		XPAR_DDR_SDRAM_0_MPMC_HIGHADDR,
		XPAR_DDR_SDRAM_0_MPMC_CTRL_BASEADDR,
		XPAR_DDR_SDRAM_0_INCLUDE_ECC_SUPPORT,
		XPAR_DDR_SDRAM_0_USE_STATIC_PHY,
		XPAR_DDR_SDRAM_0_PM_ENABLE,
		XPAR_DDR_SDRAM_0_MEM_DATA_WIDTH,
		XPAR_DDR_SDRAM_0_MEM_PART_NUM_BANK_BITS,
		XPAR_DDR_SDRAM_0_MEM_PART_NUM_ROW_BITS,
		XPAR_DDR_SDRAM_0_MEM_PART_NUM_COL_BITS,
		XPAR_DDR_SDRAM_0_MEM_DQS_WIDTH,
		XPAR_DDR_SDRAM_0_MPMC_CLK0_PERIOD_PS
	}
};


