
# ##############################################################################
# Name: system.mss
# $Rev: 10 $
# $Author: dbekker $
# $Date: 2010-03-30 17:38:09 -0700 (Tue, 30 Mar 2010) $
# Description:  This is the software system file for the iBoard.
# -
# Target Board: iBoard
# Family:       virtex5
# Device:       XC5VFX130T
# Package:      FF1738
# Speed Grade:  -1
# Processor:    ppc440_0, ppc440_1
# CPU freq:     250.00 MHz
# Bus freq:     125.00 MHz
# -
# Total Off Chip Memory : 1+ GB MB
# - DDR_SDRAM_0 = 512 MB
# - DDR_SDRAM_1 = 512 MB
# - SRAM
# - FLASH
# ##############################################################################
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 2.00.a
 PARAMETER PROC_INSTANCE = ppc440_0
 PARAMETER STDIN = RS232_0
 PARAMETER STDOUT = RS232_0
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu_ppc440
 PARAMETER DRIVER_VER = 1.01.a
 PARAMETER HW_INSTANCE = ppc440_0
 PARAMETER COMPILER = powerpc-eabi-gcc
 PARAMETER ARCHIVER = powerpc-eabi-ar
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = xps_bram_if_cntlr_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = xps_bram_if_cntlr_0_bram
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 1.14.a
 PARAMETER HW_INSTANCE = RS232_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = mpmc
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = DDR_SDRAM_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = clock_generator_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = jtagppc_cntlr_inst
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = proc_sys_reset_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = intc
 PARAMETER DRIVER_VER = 1.11.a
 PARAMETER HW_INSTANCE = xps_intc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = lltemac
 PARAMETER DRIVER_VER = 2.00.a
 PARAMETER HW_INSTANCE = Hard_Ethernet_MAC
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = llfifo
 PARAMETER DRIVER_VER = 1.01.a
 PARAMETER HW_INSTANCE = Hard_Ethernet_MAC_fifo
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = tmrctr
 PARAMETER DRIVER_VER = 1.11.a
 PARAMETER HW_INSTANCE = xps_timer_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = sysmon
 PARAMETER DRIVER_VER = 3.00.a
 PARAMETER HW_INSTANCE = xps_sysmon_adc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = qmfir
 PARAMETER DRIVER_VER = 2.00.a
 PARAMETER HW_INSTANCE = qmfir_0
END


BEGIN LIBRARY
 PARAMETER LIBRARY_NAME = ushell
 PARAMETER LIBRARY_VER = 1.00.a
 PARAMETER PROC_INSTANCE = ppc440_0
 PARAMETER interrupts = false
 PARAMETER jump = false
END

BEGIN LIBRARY
 PARAMETER LIBRARY_NAME = lwip130
 PARAMETER LIBRARY_VER = 1.00.b
 PARAMETER PROC_INSTANCE = ppc440_0
END

